# .github/workflows/run-scraper.yml
name: Run scraper on schedule

on:
  schedule:
    - cron: "0 19 * * *"   # 5:00 AM Melbourne (AEST, UTC+10)
    - cron: "0 2 * * 1-5"  # 12:00 PM Melbourne weekdays (AEST, UTC+10)
  workflow_dispatch: {}     # manual trigger

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run scraper
        run: |
          python scraper.py
